INSERT INTO FACTURA (NOMBRE) VALUES ('MOVISTAR');
INSERT INTO FACTURA (NOMBRE) VALUES ('CARREFOUR');
INSERT INTO FACTURA (NOMBRE) VALUES ('MEGATONE');
INSERT INTO FACTURA (NOMBRE) VALUES ('RIBEIRO');
